repos:
  # Remove trailing whitespaces
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(po|pot|yml|yaml|json|md)$
      - id: end-of-file-fixer
        exclude: \.(po|pot|yml|yaml|json|md)$
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files

  # Remove unused imports and variables
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
      - id: autoflake

  # Automatically sorts and groups imports
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Format with black
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        exclude : \.(po|pot|yml|yaml|json|md)$