repos:
  # Remove trailing whitespaces
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(po|pot|yml|yaml|json|md)$
      - id: end-of-file-fixer
        exclude: \.(po|pot|yml|yaml|json|md)$
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files

  # Automatically checks for language upgrades and updates code accordingly
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        exclude: \.(po|pot|yml|yaml|json|md)$

  # Remove unused imports and variables
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake

  # Automatically sorts and groups imports
  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort

  # Format with black
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: [--safe, --quiet]
        exclude: \.(po|pot|yml|yaml|json|md)$